baseURL = "https://simonaubury.com/"
languageCode = 'en-au'
title = 'Simon Aubury'
theme = 'aether'
googleAnalytics = "G-7N67PMRZ6N"

[params]
  brand = "simon aubury"
  description = "Personal website for Simon Aubury"
  headshotimg = "simon-aubury-profile.jpg"
  headshotalt = "Simon Aubury photo"
  rssinmenu = true
  github = "https://github.com/saubury"
  linkedin = "https://www.linkedin.com/in/simonaubury"


[markup]
  [markup.highlight]
    style = "igor"
