name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
# the default is to pull the latest version
        HUGO_VERSION: 0.108.0
        TARGET_REPO: saubury/saubury.github.io
        TOKEN: ${{ secrets.DEPLOY_HUGO_TOKEN }}
        CNAME: simonaubury.com
